export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const SET_PROJECTS = "SET_PROJECTS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";
export const TO_CLASSES_PAGE = "TO_CLASSES_PAGE";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const SIGNIN = "SIGNIN";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const LOGOUT = "LOGOUT";
export const INIT = "INIT";

export const SET_CLIENT_FIRST_NAME = "SET_CLIENT_FIRST_NAME";
export const SET_CLIENT_FAMILY_NAME = "SET_CLIENT_FAMILY_NAME";
export const SET_CLIENT_EMAIL = "SET_CLIENT_EMAIL";
export const SET_CLIENT_PHONE = "SET_CLIENT_PHONE";
export const SET_CLIENT_POSTAL_CODE = "SET_CLIENT_POSTAL_CODE";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_PASSWORD = "SET_PASSWORD";

export const INVALID_EMAIL = "INVALID_EMAIL";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const INVALID_FIRST_NAME = "INVALID_FIRST_NAME";
export const INVALID_FAMILY_NAME = "INVALID_FAMILY_NAME";
export const INVALID_PHONE = "INVALID_PHONE";
export const INVALID_POSTAL_CODE = "INVALID_POSTAL_CODE";
export const SIGN_UP = "SIGN_UP";
export const PASSWORD_DONT_MATCH = "PASSWORD_DONT_MATCH";
export const RESET_EMAIL = "RESET_EMAIL";
export const RESET_PASSWORD_ERRORS = "RESET_PASSWORD_ERRORS";
export const RESET_POSTAL_CODE = "RESET_POSTAL_CODE";
export const RESET_USER_DATA = "RESET_USER_DATA";

export const LOAD_NEW_IMAGE = "LOAD_NEW_IMAGE";
export const SET_SELECTED_CLASS = "SET_SELECTED_CLASS";

export const SET_PRICING_PLANS = "SET_PRICING_PLANS";

export const SET_UPLOADED = "SET_UPLOADED";
export const SET_UNZIPPED = "SET_UNZIPPED";
export const SET_PROCESSED = "SET_PROCESSED";
export const SET_ERROR = "SET_ERROR";
